apiVersion: v1
kind: Service
metadata:
  name: gnb-{{ .Release.Name }}-svc
  labels:
    app: ueransim-gnb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gnb-sctp
      port: 38412
      targetPort: 38412
      protocol: SCTP
    - name: gnb-upf #ADD
      port: 2152
      protocol: UDP
  selector:
    app: ueransim-gnb
